services:
  - type: web
    name: trustpilot-app
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: bash app/start_app.sh
    autoDeploy: false   # on déploie via Deploy Hook après que les tests passent
    envVars:
      - key: ENV
        value: prod
      - key: RENDER
        value: "true"
      
    postdeploy: |
      FLASK_APP=app:create_app flask db upgrade --directory app/migrations
