services:
  - type: web
    name: trustpilot-app
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 3 --log-level info
    autoDeploy: false   # on déploie via Deploy Hook après que les tests passent
    envVars:
      - key: ENV
        value: prod
      - key: RENDER
        value: "true"
      # API_BASE_URL sera défini dans Render Settings → Environment
    postdeploy: |
      FLASK_APP=app:create_app flask db upgrade --directory app/migrations
