services:
  - type: web
    name: trustpilot-app
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: python create_users.py
    autoDeploy: true
    envVars:
      - key: ENV
        value: prod
      - key: RENDER
        value: "true"
    postdeploy: |
      FLASK_APP=app:create_app flask db upgrade --directory app/migrations
