services:
  - type: web
    name: trustpilot-app
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --log-level info app.run_app:app 
    autoDeploy: true
    envVars:
      - key: ENV
        value: prod
      - key: RENDER
        value: "true"
      - key: API_BASE_URL
        value: "{{.Service.trustpilot-api.PublicUrl}}"
    postdeploy: |
      FLASK_APP=app:create_app flask db upgrade --directory app/migrations
