services:
  - type: web
    name: trustpilot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: false  # déploiement déclenché par Deploy Hook après tests
    envVars:
      - key: ENV
        value: prod
      - key: RENDER
        value: "true"
