name: CD (Render Deploy + Smoke)

on:
  # Lance manuellement si besoin
  workflow_dispatch:
  # Se lance automatiquement après succès du workflow "Python Tests" sur main
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    # Ne déploie que si les tests sont PASS
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy - API
        run: curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_API }}"
      - name: Trigger Render deploy - APP
        run: curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_APP }}"

  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for API to be healthy
        run: |
          for i in {1..30}; do
            if curl -fsS https://trustpilot-api.onrender.com/api/dashboard/health >/dev/null; then
              echo "API OK"; exit 0; fi
            echo "waiting API..."; sleep 10;
          done
          echo "API failed to become healthy" >&2; exit 1

      - name: Wait for App to be healthy
        run: |
          for i in {1..30}; do
            if curl -fsS https://my-feedback-app-q9l9.onrender.com/healthz >/dev/null; then
              echo "APP OK"; exit 0; fi
            echo "waiting APP..."; sleep 10;
          done
          echo "APP failed to become healthy" >&2; exit 1
